### ISSUE TITLE
Remove Left Padding when using dynamic Snap alignment position

### ISSUE THREAD

**Issue by abenezeryohannes** [polarby/snappy_list_view#3] opened 2022-11-05 09:18 UTC
https://user-images.githubusercontent.com/30086606/200112554-51a96e6d-a85d-454d-888a-04a0682a8bb5.mp4
Hi there. need help on this.
when I use "snapAlignment: SnapAlignment.moveAcross()" and "snapOnItemAlignment: SnapAlignment.moveAcross()," and the number of items are small I get empty space at the left but as u can see there is no empty space at the right end side of the list which is great. how can i remove the left side padding/empty space.

**Comment by polarby** [comment] 2022-11-05 10:47
Looking into it right now.

**Comment by polarby** [comment] 2022-11-05 10:53
I don't quite understand your problem, yet. When does the empty space appear? Does it appear only on the left side? When scrolling to the end of the list? 

Generally, an empty space appears, because the Widget is trying to center/move items to their appropriate snap position. So especially on border items empty space is used to compensate for the movement to the snap point. Are you suggesting that the scroll direction viewport-size of the SnappyListView should dynamically change size? What is your expected behavior?

Also: I am having trouble loading your video. Do you mind providing the video with a different source? (not listed youtube video, Vimeo, Imgur) This might clarify what you mean.

**Comment by abenezeryohannes** [comment] 2022-11-05 18:35
Ok let me explain I am making an app that needs to implement tab view like airbnb app home page. Thanks to you I am very close to doing that but the only problem is when I scroll 1 or 2 times I will end up with unwanted extea eft padding specially you will see that when the list is small like 5 or 6 items here is the image that can showcase it best
![Screenshot_20221105_212555_Chrome](https://user-images.githubusercontent.com/30086606/200135598-a64d3413-1b51-4b24-ac1d-a003c9cb1b2f.jpg)

**Comment by polarby** [comment] 2022-11-06 03:14
I tried it out with smaller and fewer items in the `example.dart` but couldn't reproduce this false empty space you are showing.

Do you mind providing me with a working source code, so I can debug it?!

Also on what version are running it?

**Comment by polarby** [comment] 2022-11-15 12:15
Did you figure out what cause your behavior? Is the bug still present? Otherwise I will close the issue.

**Comment by polarby** [comment] 2022-11-20 07:44
Closed as no further elaboration.

**Closed as completed by polarby** 2022-11-20 07:44 UTC
Labels: bug, help wanted, awaiting response
